server:
  port: 8888
spring:
  application:
    name: rest-with-spring-boot
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  flyway:
    schemas: rest-with-spring-boot
    default-schema: rest-with-spring-boot
logging:
  level:
    root: INFO
    com.lcmuniz.rest_with_spring_boot: DEBUG

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 3600000

